### ISSUE TITLE
Cannot find source file:miracl/big.cpp

### ISSUE THREAD

**Issue by Gaturae** [AcherStyx/SM2#1]
是不是我还要下载miracl库放在根目录下，我是win10环境

**Comment by Yaojie-Shen** [comment]
> 是不是我还要下载miracl库放在根目录下，我是win10环境

有一个安装的shell脚本，用于linux系统下miracl的安装配置。如果是windows环境下的话，麻烦您自行搜索资料配置。

**Comment by Yaojie-Shen** [comment]
另外运行方面，没有提供相应的可执行文件，仅在头文件和代码内以函数形式封装了SM2的加解密和签名算法，使用方式可以参照对应的测试用例。

**Comment by Yaojie-Shen** [comment]
没有问题的话我先close了
